import {
  poppins,
  lato,
  cinzelDecorative,
  tangerine,
  sacramento,
  greatVibes,
  sourceCodePro,
  ibmPlexMono,
  notoSansDevanagari,
  hind,
} from '@/lib/fonts';

import "./globals.css";
import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark h-full w-full">
      <body className={
        `${geistSans.variable}
        antialiased h-full w-full
        ${geistMono.variable} 
        ${poppins.variable}
        ${lato.variable}
        ${cinzelDecorative.variable}
        ${tangerine.variable}
        ${sacramento.variable}
        ${greatVibes.variable}
        ${sourceCodePro.variable}
        ${ibmPlexMono.variable}
        ${notoSansDevanagari.variable}
        ${hind.variable}`}
      >
        {children}
        <Toaster />
      </body>
    </html >
  );
}
